# Generated by Django 4.1 on 2022-11-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_section_relationship_article_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
